Sleep(3000)
ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","C:\Users\Shree\eclipse-workspace\LinkedIn_AutomateDDFramework\src\main\resources\repository\AutoImage.jpg")
Sleep(3000)
ControlClick("Open","","Button1")
Sleep(3000)